---
queue: bazel-lib-small
env:
  CC: /bin/false
workspaces:
  .:
    tasks:
      - test:
          queue: bazel-lib
  e2e/smoke:
    icon: bazel
    tasks:
      - format:
          without: true
      - gazelle:
          without: true
      # - configure:
      #     without: true
      - buildifier:
          without: true
      - delivery:
          without: true
  e2e/coreutils:
    icon: bazel
    tasks:
      - format:
          without: true
      - gazelle:
          without: true
      # - configure:
      #     without: true
      - buildifier:
          without: true
      - delivery:
          without: true
  e2e/copy_to_directory:
    icon: bazel
    tasks:
      - format:
          without: true
      - gazelle:
          without: true
      # - configure:
      #     without: true
      - buildifier:
          without: true
      - delivery:
          without: true
  e2e/external_copy_to_directory:
    icon: bazel
    tasks:
      - format:
          without: true
      - gazelle:
          without: true
      # - configure:
      #     without: true
      - buildifier:
          without: true
      - delivery:
          without: true
tasks:
  - test:
  - format:
  - gazelle:
  # - configure:
  - buildifier:
  - delivery:
      queue: bazel-lib
      always_deliver: true
