---
queue: bazel-lib
env:
  CC: /bin/false
workspaces:
  - .
  - e2e/smoke
  - e2e/coreutils
  - e2e/copy_to_directory
  - e2e/external_copy_to_directory/workspace
  - e2e/workspace
bazel:
  flags:
    - --remote_download_minimal
    - --nobuild_runfile_links
tasks:
  branch_freshness:
  test:
