---
queue: bazel-lib-default
env:
  CC: /bin/false
workspaces:
  .:
    tasks:
      - test:
  e2e/smoke:
    icon: bazel
    tasks:
      - test:
          queue: bazel-lib-small
      - format:
          without: true
      - gazelle:
          without: true
      - configure:
          without: true
      - buildifier:
          without: true
      - delivery:
          without: true
  e2e/coreutils:
    icon: bazel
    tasks:
      - test:
          queue: bazel-lib-small
      - format:
          without: true
      - gazelle:
          without: true
      - configure:
          without: true
      - buildifier:
          without: true
      - delivery:
          without: true
  e2e/copy_to_directory:
    icon: bazel
    tasks:
      - test:
          queue: bazel-lib-small
      - format:
          without: true
      - gazelle:
          without: true
      - configure:
          without: true
      - buildifier:
          without: true
      - delivery:
          without: true
  e2e/external_copy_to_directory:
    icon: bazel
    tasks:
      - test:
          queue: bazel-lib-small
      - format:
          without: true
      - gazelle:
          without: true
      - configure:
          without: true
      - buildifier:
          without: true
      - delivery:
          without: true
tasks:
  - test:
  - format:
      queue: bazel-lib-small
  - gazelle:
      queue: bazel-lib-small
  - configure:
      queue: bazel-lib-small
  - buildifier:
      queue: bazel-lib-small
  - delivery:
      queue: bazel-lib-default
      auto_deliver: true
      rules:
        - deliverable: 'attr("tags", "\bdeliverable\b", //...)'
          condition:
            branches:
              - main
        - deliverable:
            - //tools/release:tools_delivery
          condition:
            only_on_change: false
            branches:
              - main
  - warming:
      queue: bazel-lib-warming
