---
queue: bazel-lib
env:
  CC: /bin/false
workspaces:
  - .
  - e2e/smoke:
      tasks:
        format:
          without: true
        gazelle:
          without: true
        buildifier:
          without: true
  - e2e/coreutils:
      tasks:
        format:
          without: true
        gazelle:
          without: true
        buildifier:
          without: true
  - e2e/copy_to_directory:
      tasks:
        format:
          without: true
        gazelle:
          without: true
        buildifier:
          without: true
  - e2e/external_copy_to_directory:
      tasks:
        format:
          without: true
        gazelle:
          without: true
        buildifier:
          without: true
tasks:
  format:
    soft_fail: false
  gazelle:
  buildifier:
  test:
