"Setup search & displace (sd) toolchain repositories and rules"

# Platform names follow the platform naming convention in @aspect_bazel_lib//:lib/private/repo_utils.bzl
SD_PLATFORMS = {
    "darwin_amd64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
    ),
    "darwin_arm64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
    ),
    "linux_amd64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    ),
    "linux_arm64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
    ),
    "windows_amd64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
    ),
}

DEFAULT_SD_VERSION = "v1.0.0"

# https://github.com/chmln/sd
#
# The integrity hashes can be automatically fetched for the sd releases by running
# `tools/sd_mirror_release.sh`.
SD_VERSIONS = {
  "v1.0.0": {
    "darwin_arm64": {
      "filename": "sd-v1.0.0-aarch64-apple-darwin.tar.gz",
      "sha256": "sha256-p2Ssm5Zsbwz+qmbyrS1JRbCPjZPZc+0aYry/vhwn6YE="
    },
    "linux_arm64": {
      "filename": "sd-v1.0.0-aarch64-unknown-linux-musl.tar.gz",
      "sha256": "sha256-npn46d1wxwFbjCDkknC92Z6cr5ZqQaEZgvTXhfaljJ4="
    },
    "darwin_amd64": {
      "filename": "sd-v1.0.0-x86_64-apple-darwin.tar.gz",
      "sha256": "sha256-hAjrg8eYjNxyr8TRcXlSAZmbpNMhx3KJIf+FVlkV510="
    },
    "windows_amd64": {
      "filename": "sd-v1.0.0-x86_64-pc-windows-msvc.zip",
      "sha256": "sha256-t8yZN+vB9zbIfVkpueoigAU68Q+OMg2cIMqQw69GpdU="
    },
    "linux_amd64": {
      "filename": "sd-v1.0.0-x86_64-unknown-linux-musl.tar.gz",
      "sha256": "sha256-n0Lk/seEj6jW7qt7EJD1ycnjdMlKmXTbb/M98FLJ4TI="
    }
  }
}

SdInfo = provider(
    doc = "Provide info for executing sd",
    fields = {
        "bin": "Executable sd binary",
    },
)

def _sd_toolchain_impl(ctx):
    binary = ctx.file.binary

    # Make the $(SD_BIN) variable available in places like genrules.
    # See https://docs.bazel.build/versions/main/be/make-variables.html#custom_variables
    template_variables = platform_common.TemplateVariableInfo({
        "SD_BIN": binary.path,
    })
    default_info = DefaultInfo(
        files = depset([binary]),
        runfiles = ctx.runfiles(files = [binary]),
    )
    sd_info = SdInfo(
        bin = binary,
    )

    # Export all the providers inside our ToolchainInfo
    # so the resolved_toolchain rule can grab and re-export them.
    toolchain_info = platform_common.ToolchainInfo(
        sd_info = sd_info,
        template_variables = template_variables,
        default = default_info,
    )

    return [default_info, toolchain_info, template_variables]

sd_toolchain = rule(
    implementation = _sd_toolchain_impl,
    attrs = {
        "binary": attr.label(
            mandatory = True,
            allow_single_file = True,
        ),
    },
)

def _sd_toolchains_repo_impl(rctx):
    # Expose a concrete toolchain which is the result of Bazel resolving the toolchain
    # for the execution or target platform.
    # Workaround for https://github.com/bazelbuild/bazel/issues/14009
    starlark_content = """# @generated by @aspect_bazel_lib//lib/private:sd_toolchain.bzl

# Forward all the providers
def _resolved_toolchain_impl(ctx):
    toolchain_info = ctx.toolchains["@aspect_bazel_lib//lib:sd_toolchain_type"]
    return [
        toolchain_info,
        toolchain_info.default,
        toolchain_info.sd_info,
        toolchain_info.template_variables,
    ]

# Copied from java_toolchain_alias
# https://cs.opensource.google/bazel/bazel/+/master:tools/jdk/java_toolchain_alias.bzl
resolved_toolchain = rule(
    implementation = _resolved_toolchain_impl,
    toolchains = ["@aspect_bazel_lib//lib:sd_toolchain_type"],
    incompatible_use_toolchain_transition = True,
)
"""
    rctx.file("defs.bzl", starlark_content)

    build_content = """# @generated by @aspect_bazel_lib//lib/private:sd_toolchain.bzl
#
# These can be registered in the workspace file or passed to --extra_toolchains flag.
# By default all these toolchains are registered by the sd_register_toolchains macro
# so you don't normally need to interact with these targets.

load(":defs.bzl", "resolved_toolchain")

resolved_toolchain(name = "resolved_toolchain", visibility = ["//visibility:public"])

"""

    for [platform, meta] in SD_PLATFORMS.items():
        build_content += """
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:sd_toolchain",
    toolchain_type = "@aspect_bazel_lib//lib:sd_toolchain_type",
)
""".format(
            platform = platform,
            user_repository_name = rctx.attr.user_repository_name,
            compatible_with = meta.compatible_with,
        )

    # Base BUILD file for this repository
    rctx.file("BUILD.bazel", build_content)

sd_toolchains_repo = repository_rule(
    _sd_toolchains_repo_impl,
    doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
    attrs = {
        "user_repository_name": attr.string(doc = "Base name for toolchains repository"),
    },
)

def _sd_platform_repo_impl(rctx):
    is_windows = rctx.attr.platform.startswith("windows_")
    platform = rctx.attr.platform
    filename = SD_VERSIONS[rctx.attr.version][platform]["filename"]
    url = "https://github.com/chmln/sd/releases/download/{}/{}".format(
        rctx.attr.version,
        filename,
    )
    rctx.download_and_extract(
        url = url,
        stripPrefix = filename.replace(".zip", "").replace(".tar.gz", ""),
        integrity = SD_VERSIONS[rctx.attr.version][platform]["sha256"],
    )
    build_content = """# @generated by @aspect_bazel_lib//lib/private:sd_toolchain.bzl
load("@aspect_bazel_lib//lib/private:sd_toolchain.bzl", "sd_toolchain")
exports_files(["{0}"])
sd_toolchain(name = "sd_toolchain", binary = "{0}", visibility = ["//visibility:public"])
""".format("sd.exe" if is_windows else "sd")

    # Base BUILD file for this repository
    rctx.file("BUILD.bazel", build_content)

sd_platform_repo = repository_rule(
    implementation = _sd_platform_repo_impl,
    doc = "Fetch external tools needed for sd toolchain",
    attrs = {
        "version": attr.string(mandatory = True, values = SD_VERSIONS.keys()),
        "platform": attr.string(mandatory = True, values = SD_PLATFORMS.keys()),
    },
)
